### ISSUE TITLE
Wikidata tagged as "unavailable" for species that has a Wikidata item

### ISSUE THREAD

**Issue by Daniel-Mietchen** [jdlrobson/WikiLovesINat#3]
as per
https://wikilovesinat.netlify.com/#34903
and
https://www.wikidata.org/w/index.php?title=Q641503&oldid=873180381#P3151

**Comment by jdlrobson** [comment]
So the issue here is that iNaturalist page (https://www.inaturalist.org/taxa/109180-Petracola-waka) doesn't have a Wikipedia link associated -  (and I'm not sure how to fix that!). For now I'm linking to Wikipedia via https://en.wikipedia.org/wiki/Special:Search?search=Petracola

How can we fix iNaturalist to link to Wikipedia?

**Comment by jdlrobson** [comment]
See e30798991aeea7566c1aec2a1339243e128dd978

**Comment by jdlrobson** [comment]
So it looks like the problem is for iNaturalist the canonical URL is English Wikipedia NOT wikidata.
There is no English article for Petracola Waka https://www.wikidata.org/wiki/Q3377598

So to fix this we will need to either
1) Get iNaturalist to use Wikidata links as the canonical source of content.
2) Create an article on English Wikipedia for Petracola Waka.

**Comment by jdlrobson** [comment]
Without iNaturalist making wikidata the canonical wikimedia identifier rather than English Wikipedia I can't do much here.  The copy text now makes it much clearer when I don't know about the wikidata ID or Wikipedia URL, but please feel free to open a new issue if you have any other ideas on how I can improve on this!
