### ISSUE TITLE
Refine search by license type

### ISSUE THREAD

**Issue by Loopy30** [jdlrobson/WikiLovesINat#8]
Hi Jon, as a Wikipedia editor looking to improve articles on different species, I thank you for writing this program/webpage.

Presently, when I search for Wikipedia articles that lack images, I get a list of five article titles and a sliding bar underneath indicating many more. If I select one of these articles, it may then indicate that there are no iNat images for that subject, or the images may be grayed out indicating that they do not have the appropriate Creative Commons license to be used on Wikipedia.

As my goal is to find images on iNat that I can legally share on Wikipedia articles, is there a way to refine the search such that only species that meet all of the following conditions are displayed?
1) The (English) Wikipedia article currently has no image.
2) An iNat observation has an image 
3) The iNat image has an allowable license to share on Wikipedia (i.e. CC-BY-SA, CC-BY, or CC0)

Thanks,
PJ

**Comment by jdlrobson** [comment]
I will look into this within the next week. Sorry for the delayed response here.

**Comment by Loopy30** [comment]
OK great. Thanks,

**Comment by jdlrobson** [comment]
So I reminded myself of the problem here :) This is unfortunately an existing limitation of thj etool.

So while we can tell which articles lack images on Wikipedia/Wikidata we can't easily tell which of those have associated iNaturalist photos (And thus cannot tell which ones have freely licensed photos) which was effectively the point of the tool - to allow editors to manually explore and determine which ones do (which is why as you click the boxes they disappear and do not load on future page views.

<img width="300" alt="Screen Shot 2021-10-01 at 1 43 23 PM" src="https://user-images.githubusercontent.com/148752/135683986-f8fdba77-97b7-4a81-be56-e12cf23ce089.png">

If I was to query all of them automatically on behalf of the user, I would have to do a query to iNaturalist for every single one of those gray boxes and without being careful that's likely to get the user emporarily banned from iNaturalist for going over the rate limits for requesting photos (I just did this myself hehe)

Something that would help is if the iNaturalist API supported batch queries. I'll keep thinking around how to work around the limitations here to make this workflow require less manual work.

**Comment by Loopy30** [comment]
Ok, thanks.

The other issue was that the taxa offered by the tool did not seem to be in
any sort of obvious sequence (maybe they were by iNaturalist taxon ID
numbers or something?). Nor did there seem to be any way of methodically
going through the list and being able to know where in the list you were at
in order  to pick up where you left off from a previous visit.

Peter

**Comment by jdlrobson** [comment]
This isn't quite what you asked for, but the new version of https://wikilovesinat.netlify.app/ will now show if iNaturalist has an image (cross if it doesn't.). It also has a button which allows you to dismiss ones that iNaturalist definitely doesn't have a photo for.

There's still some manual work to do. I can't work out which have the right license, but hopefully this makes your workflow a little easier and a little more fun/rewarding. Lemme know!

**Comment by Loopy30** [comment]
Thanks, that helps.
