### ISSUE TITLE
I was unable to locate creature with that Wikidata ID.

### ISSUE THREAD

**Issue by SednaBoo** [jdlrobson/WikiLovesINat#9]
I get this error when searching by Wikidata ID:
> I was unable to locate creature with that Wikidata ID.
This appears for:
_Astragalus crassicarpus_ var. _trichocalyx_ (Q67194950)
_Sambucus racemosa_ subsp. _pubens_ (Q3470723)

However, the tool worked for other infraspecific taxa that i tried such as:
_Hackelia deflexa_ var. _americana_ (Q67196197)
Sangamon phlox (Q49459905) 

These all have pages on iNaturalist.

**Comment by jdlrobson** [comment]
will look into this within the next week. Sorry for the delayed response here.

**Comment by jdlrobson** [comment]
The error occurs when the Wikidata item has no iNaturalist taxon iD.
e.g. https://www.wikidata.org/w/index.php?title=Q67194950&type=revision&diff=1506413809&oldid=1317890352

I've improved the error message to make this clearer so users that run into this  can fix up the Wikidata item so that they can use the tool. Thanks for reporting!

**Comment by SednaBoo** [comment]
Got it.  Thanks!
